export const SET_BOOLEAN_WIDGET_VALUES = 'SET_BOOLEAN_WIDGET_VALUES';
export const FILTER_BOOLEAN_WIDGET_DEVICES = 'FILTER_BOOLEAN_WIDGET_DEVICES';
export const SET_BOOLEAN_WIDGET_EDIT_MODE = 'SET_BOOLEAN_WIDGET_EDIT_MODE';
export const SET_BOOLEAN_WIDGET_DATA = 'SET_BOOLEAN_WIDGET_DATA';