// Fetch all buildings
export const GET_BUILDINGS = "GET_BUILDINGS"
export const GET_BUILDINGS_SUCCESS = "GET_BUILDINGS_SUCCESS"
export const START_LOAD_BUILDINGS = "START_LOAD_BUILDINGS"
export const END_LOAD_BUILDINGS = "END_LOAD_BUILDINGS"
export const GET_BUILDING_ASSET = "GET_BUILDING_ASSET"
export const GET_BUILDING_ASSET_SUCCESS = "GET_BUILDING_ASSET_SUCCESS"
export const GET_FLOOR_SUCCESS = "GET_BUILDING_SUCCESS"
export const GET_BUILDING_USERS = "GET_BUILDING_USERS"
export const GET_BUILDING_USERS_SUCCESS = "GET_BUILDING_USERS_SUCCESS"
export const CREATE_BUILDING_ASSET = "CREATE_BUILDING_ASSET"
export const CREATE_BUILDING_ASSET_SUCCESS = "CREATE_BUILDING_ASSET_SUCCESS"
export const END_SAVE_BUILDING = "END_SAVE_BUILDING"
export const UPDATE_BUILDING_ASSET = "UPDATE_BUILDING_ASSET"
export const UPDATE_BUILDING_ASSET_SUCCESS = "UPDATE_BUILDING_ASSET_SUCCESS"
export const DELETE_BUILDING_ASSET = "DELETE_BUILDING_ASSET"
export const DELETE_BUILDING_ASSET_SUCCESS = "DELETE_BUILDING_ASSET_SUCCESS"
export const CLEAR_BUILDINGS = "CLEAR_BUILDINGS"
export const ASSIGN_BUILDING_USER = "ASSIGN_BUILDING_USER"
export const UPDATE_BUILDING_USER = "UPDATE_BUILDING_USER"
export const DELETE_BUILDING_USER = "DELETE_BUILDING_USER"
export const UPDATE_BUILDING_DEVICES = "UPDATE_BUILDING_DEVICES"
export const UPDATE_BUILDING_DEVICES_SUCCESS = "UPDATE_BUILDING_DEVICES_SUCCESS"
export const ASSIGN_BUILDING_USER_SUCCESS = "ASSIGN_BUILDING_USER_SUCCESS"
export const SET_SELECTED_BUILDING_ID = "SET_SELECTED_BUILDING_ID"




