export const icons = [
  "uil-grid",
  "uil-grids",
  "uil-web-grid-alt",
  "uil-web-grid",
  "uil-window-grid",
  "uil-clapper-board",
  "uil-desktop-alt-slash",
  "uil-desktop-alt",
  "uil-desktop-cloud-alt",
  "uil-desktop-slash",
  "uil-desktop",
  "uil-abacus",
  "uil-accessible-icon-alt",
  "uil-adjust-alt",
  "uil-adjust-circle",
  "uil-adjust-half",
  "uil-adjust",
  "uil-adobe-alt",
  "uil-adobe",
  "uil-airplay",
  "uil-align-alt",
  "uil-align-center-alt",
  "uil-align-center-h",
  "uil-align-center-justify",
  "uil-align-center-v",
  "uil-align-justify",
  "uil-align-center",
  "uil-align-left-justify",
  "uil-align-left",
  "uil-align-letter-right",
  "uil-align-right",
  "uil-align",
  "uil-amazon",
  "uil-ambulance",
  "uil-analysis",
  "uil-analytics",
  "uil-anchor",
  "uil-android-alt",
  "uil-android-phone-slash",
  "uil-android",
  "uil-angle-double-down",
  "uil-angle-double-left",
  "uil-angle-double-right",
  "uil-angle-double-up",
  "uil-angle-down",
  "uil-angle-left",
  "uil-angle-right-b",
  "uil-angle-right",
  "uil-angry",
  "uil-ankh",
  "uil-annoyed-alt",
  "uil-annoyed",
  "uil-apple-alt",
  "uil-apple",
  "uil-apps",
  "uil-archive",
  "uil-archway",
  "uil-arrow-break",
  "uil-arrow-circle-down",
  "uil-arrow-circle-left",
  "uil-arrow-circle-right",
  "uil-arrow-circle-up",
  "uil-arrow-compress-h",
  "uil-arrow-down-left",
  "uil-arrow-down-right",
  "uil-arrow-down",
  "uil-arrow-from-right",
  "uil-arrow-from-top",
  "uil-arrow-growth",
  "uil-arrow-left",
  "uil-arrow-random",
  "uil-arrow-resize-diagonal",
  "uil-arrow-right",
  "uil-arrow-to-bottom",
  "uil-arrow-to-right",
  "uil-arrow-up-left",
  "uil-arrow-up-right",
  "uil-arrow-up",
  "uil-arrow",
  "uil-arrows-h-alt",
  "uil-arrows-h",
  "uil-arrows-left-down",
  "uil-arrows-maximize",
  "uil-arrows-merge",
  "uil-arrows-resize-h",
  "uil-arrows-resize-v",
  "uil-arrows-resize",
  "uil-arrows-right-down",
  "uil-arrows-shrink-h",
  "uil-arrows-shrink-v",
  "uil-arrows-v-alt",
  "uil-arrows-v",
  "uil-assistive-listening-systems",
  "uil-asterisk",
  "uil-at",
  "uil-at",
  "uil-atom",
  "uil-auto-flash",
  "uil-award-alt",
  "uil-award",
  "uil-baby-carriage",
  "uil-backpack",
  "uil-backspace",
  "uil-backward",
  "uil-bag-alt",
  "uil-bag-slash",
  "uil-bag",
  "uil-balance-scale",
  "uil-ban",
  "uil-bars",
  "uil-baseball-ball",
  "uil-basketball-hoop",
  "uil-basketball",
  "uil-bath",
  "uil-battery-bolt",
  "uil-battery-empty",
  "uil-bed-double",
  "uil-bed",
  "uil-behance-alt",
  "uil-behance",
  "uil-bell-school",
  "uil-bell-slash",
  "uil-bell",
  "uil-bill",
  "uil-bitcoin-alt",
  "uil-bitcoin-circle",
  "uil-bitcoin",
  "uil-black-berry",
  "uil-blogger-alt",
  "uil-blogger",
  "uil-bluetooth-b",
  "uil-bold",
  "uil-bolt-alt",
  "uil-bolt-slash",
  "uil-bolt",
  "uil-book-alt",
  "uil-book-medical",
  "uil-book-open",
  "uil-book-reader",
  "uil-book",
  "uil-bookmark-full",
  "uil-bookmark",
  "uil-books",
  "uil-boombox",
  "uil-border-alt",
  "uil-border-bottom",
  "uil-border-clear",
  "uil-border-horizontal",
  "uil-border-inner",
  "uil-border-left",
  "uil-border-out",
  "uil-border-right",
  "uil-border-top",
  "uil-border-vertical",
  "uil-bowling-ball",
  "uil-box",
  "uil-arrow-down",
  "uil-briefcase",
  "uil-brightness-minus",
  "uil-brightness-plus",
  "uil-brightness",
  "uil-bring-bottom",
  "uil-bring-front",
  "uil-brush-alt",
  "uil-bug",
  "uil-building",
  "uil-bullseye",
  "uil-bus-alt",
  "uil-bus-school",
  "uil-bus",
  "uil-calculator-alt",
  "uil-calculator",
  "uil-calendar-alt",
  "uil-calendar-slash",
  "uil-calender",
  "uil-calling",
  "uil-camera-change",
  "uil-camera-plus",
  "uil-camera-slash",
  "uil-camera",
  "uil-cancel",
  "uil-capsule",
  "uil-capture",
  "uil-car-sideview",
  "uil-car-slash",
  "uil-car-wash",
  "uil-car",
  "uil-card-atm",
  "uil-caret-right",
  "uil-cell",
  "uil-celsius",
  "uil-chart-bar-alt",
  "uil-chart-bar",
  "uil-chart-down",
  "uil-chart-growth-alt",
  "uil-chart-growth",
  "uil-chart-line",
  "uil-chart-pie-alt",
  "uil-chart-pie",
  "uil-chart",
  "uil-chat-bubble-user",
  "uil-chat-info",
  "uil-chat",
  "uil-check-circle",
  "uil-check-square",
  "uil-check",
  "uil-arrow-down",
  "uil-circle-layer",
  "uil-circle",
  "uil-circuit",
  "uil-clipboard-alt",
  "uil-clipboard-blank",
  "uil-clipboard-notes",
  "uil-clipboard",
  "uil-clock-eight",
  "uil-clock-five",
  "uil-clock-nine",
  "uil-clock-seven",
  "uil-clock-ten",
  "uil-clock-three",
  "uil-clock-two",
  "uil-clock",
  "uil-closed-captioning",
  "uil-cloud-block",
  "uil-arrow-down",
  "uil-cloud-bookmark",
  "uil-cloud-check",
  "uil-cloud-computing",
  "uil-cloud-data-connection",
  "uil-cloud-database-tree",
  "uil-cloud-download",
  "uil-cloud-drizzle",
  "uil-arrow-down",
  "uil-cloud-exclamation",
  "uil-cloud-hail",
  "uil-cloud-heart",
  "uil-cloud-info",
  "uil-cloud-lock",
  "uil-cloud-meatball",
  "uil-cloud-moon-hail",
  "uil-cloud-moon-meatball",
  "uil-cloud-moon-rain",
  "uil-cloud-moon-showers",
  "uil-cloud-moon",
  "uil-cloud-question",
  "uil-cloud-rain-sun",
  "uil-cloud-rain",
  "uil-cloud-redo",
  "uil-cloud-share",
  "uil-cloud-shield",
  "uil-cloud-showers-alt",
  "uil-cloud-showers-heavy",
  "uil-cloud-showers",
  "uil-cloud-slash",
  "uil-cloud-sun-hail",
  "uil-cloud-sun-meatball",
  "uil-cloud-sun-rain-alt",
  "uil-cloud-sun-rain",
  "uil-cloud-sun-tear",
  "uil-cloud-sun",
  "uil-cloud-times",
  "uil-cloud-unlock",
  "uil-cloud-upload",
  "uil-cloud-wifi",
  "uil-cloud-wind",
  "uil-cog",
  "uil-coins",
  "uil-columns",
  "uil-comment-alt-block",
  "uil-comment-alt-chart-lines",
  "uil-comment-alt-check",
  "uil-comment-alt-dots",
  "uil-comment-alt-download",
  "uil-comment-alt-edit",
  "uil-comment-alt-exclamation",
  "uil-comment-alt-heart",
  "uil-comment-alt-image",
  "uil-comment-alt-info",
  "uil-comment-alt-lines",
  "uil-comment-alt-lock",
  "uil-comment-alt-medical",
  "uil-comment-alt-message",
  "uil-comment-alt-notes",
  "uil-comment-alt-plus",
  "uil-comment-alt-question",
  "uil-comment-alt-redo",
  "uil-comment-alt-search",
  "uil-comment-alt-share",
  "uil-comment-alt-shield",
  "uil-comment-alt-slash",
  "uil-comment-alt-upload",
  "uil-comment-alt-verify",
  "uil-comment-alt",
  "uil-comment-block",
  "uil-comment-chart-line",
  "uil-comment-check",
  "uil-comment-dots",
  "uil-arrow-down",
  "uil-comment-download",
  "uil-comment-edit",
  "uil-comment-exclamation",
  "uil-comment-heart",
  "uil-comment-image",
  "uil-comment-info-alt",
  "uil-comment-info",
  "uil-comment-lines",
  "uil-comment-lock",
  "uil-comment-medical",
  "uil-comment-message",
  "uil-comment-notes",
  "uil-comment-plus",
  "uil-comment-question",
  "uil-comment-redo",
  "uil-comment-search",
  "uil-comment-share",
  "uil-comment-shield",
  "uil-comment-slash",
  "uil-comment-upload",
  "uil-comment-verify",
  "uil-comment",
  "uil-comments-alt",
  "uil-comments",
  "uil-compact-disc",
  "uil-compass",
  "uil-compress-alt-left",
  "uil-compress-alt",
  "uil-compress-arrows",
  "uil-compress-lines",
  "uil-compress-point",
  "uil-compress-v",
  "uil-compress",
  "uil-confused",
  "uil-constructor",
  "uil-copy-alt",
  "uil-copy-landscape",
  "uil-copy",
  "uil-copyright",
  "uil-corner-down-left",
  "uil-corner-down-right-alt",
  "uil-corner-down-right",
  "uil-corner-left-down",
  "uil-corner-right-down",
  "uil-corner-up-left-alt",
  "uil-corner-up-left",
  "uil-corner-up-right-alt",
  "uil-corner-up-right",
  "uil-creative-commons-pd",
  "uil-crockery",
  "uil-crop-alt-rotate-left",
  "uil-crop-alt-rotate-right",
  "uil-crop-alt",
  "uil-crosshair-alt",
  "uil-crosshair",
  "uil-crosshairs",
  "uil-cube",
  "uil-dashboard",
  "uil-data-sharing",
  "uil-database-alt",
  "uil-compass",
  "uil-database",
  "uil-desert",
  "uil-dialpad-alt",
  "uil-dialpad",
  "uil-diamond",
  "uil-diary-alt",
  "uil-diary",
  "uil-dice-five",
  "uil-dice-four",
  "uil-dice-one",
  "uil-dice-six",
  "uil-dice-three",
  "uil-dice-two",
  "uil-direction",
  "uil-directions",
  "uil-dizzy-meh",
  "uil-dna",
  "uil-document-layout-left",
  "uil-document-layout-right",
  "uil-dollar-alt",
  "uil-dollar-sign-alt",
  "uil-dollar-sign",
  "uil-download-alt",
  "uil-dribbble",
  "uil-dropbox",
  "uil-dumbbell",
  "uil-ear",
  "uil-edit-alt",
  "uil-edit",
  "uil-ellipsis-h",
  "uil-ellipsis-v",
  "uil-emoji",
  "uil-enter",
  "uil-envelope-add",
  "uil-envelope-alt",
  "uil-envelope-block",
  "uil-envelope-bookmark",
  "uil-envelope-check",
  "uil-envelope-download-alt",
  "uil-envelope-download",
  "uil-envelope-edit",
  "uil-envelope-exclamation",
  "uil-envelope-heart",
  "uil-envelope-info",
  "uil-envelope-lock",
  "uil-envelope-minus",
  "uil-envelope-open",
  "uil-envelope-question",
  "uil-envelope-receive",
  "uil-envelope-redo",
  "uil-envelope-search",
  "uil-envelope-send",
  "uil-envelope-share",
  "uil-envelope-shield",
  "uil-envelope-star",
  "uil-envelope-times",
  "uil-envelope-upload-alt",
  "uil-envelope-upload",
  "uil-envelope",
  "uil-envelopes",
  "uil-equal-circle",
  "uil-euro-circle",
  "uil-euro",
  "uil-exchange-alt",
  "uil-exchange",
  "uil-exclamation-circle",
  "uil-exclamation-octagon",
  "uil-exclamation-triangle",
  "uil-exclude",
  "uil-expand-alt",
  "uil-expand-arrows-alt",
  "uil-expand-arrows",
  "uil-expand-from-corner",
  "uil-expand-left",
  "uil-expand-right",
  "uil-export",
  "uil-exposure-alt",
  "uil-exposure-increase",
  "uil-external-link-alt",
  "uil-eye-slash",
  "uil-eye",
  "uil-facebook-f",
  "uil-facebook-messenger-alt",
  "uil-facebook-messenger",
  "uil-facebook",
  "uil-fahrenheit",
  "uil-fast-mail-alt",
  "uil-fast-mail",
  "uil-favorite",
  "uil-feedback",
  "uil-file-alt",
  "uil-file-blank",
  "uil-file-block-alt",
  "uil-file-bookmark-alt",
  "uil-file-check-alt",
  "uil-file-check",
  "uil-file-contract-dollar",
  "uil-file-copy-alt",
  "uil-file-download-alt",
  "uil-file-download",
  "uil-file-edit-alt",
  "uil-file-exclamation-alt",
  "uil-file-exclamation",
  "uil-file-heart",
  "uil-file-info-alt",
  "uil-file-landscape-alt",
  "uil-file-landscape",
  "uil-file-lanscape-slash",
  "uil-file-lock-alt",
  "uil-file-medical-alt",
  "uil-file-medical",
  "uil-file-minus-alt",
  "uil-file-minus",
  "uil-file-network",
  "uil-file-plus-alt",
  "uil-file-plus",
  "uil-file-question-alt",
  "uil-file-question",
  "uil-file-redo-alt",
  "uil-file-search-alt",
  "uil-file-share-alt",
  "uil-file-shield-alt",
  "uil-file-slash",
  "uil-file-times-alt",
  "uil-file-times",
  "uil-file-upload-alt",
  "uil-file-upload",
  "uil-file",
  "uil-files-landscapes-alt",
  "uil-files-landscapes",
  "uil-film",
  "uil-filter-slash",
  "uil-filter",
  "uil-fire",
  "uil-flask-potion",
  "uil-flask",
  "uil-flip-h-alt",
  "uil-flip-h",
  "uil-flip-v-alt",
  "uil-flip-v",
  "uil-flower",
  "uil-focus-add",
  "uil-focus-target",
  "uil-focus",
  "uil-folder-check",
  "uil-folder-download",
  "uil-folder-exclamation",
  "uil-folder-heart",
  "uil-folder-info",
  "uil-folder-lock",
  "uil-folder-medical",
  "uil-folder-minus",
  "uil-folder-network",
  "uil-folder-plus",
  "uil-folder-question",
  "uil-folder-slash",
  "uil-folder-times",
  "uil-folder-upload",
  "uil-folder",
  "uil-football-american",
  "uil-football-ball",
  "uil-football",
  "uil-forecastcloud-moon-tear",
  "uil-forwaded-call",
  "uil-forward",
  "uil-frown",
  "uil-game-structure",
  "uil-gift",
  "uil-github-alt",
  "uil-github",
  "uil-glass-martini-alt-slash",
  "uil-glass-martini-alt",
  "uil-glass-martini",
  "uil-compass",
  "uil-glass-tea",
  "uil-glass",
  "uil-globe",
  "uil-gold",
  "uil-google-drive-alt",
  "uil-google-drive",
  "uil-google-hangouts-alt",
  "uil-google-hangouts",
  "uil-google-play",
  "uil-google",
  "uil-graph-bar",
  "uil-grin-tongue-wink-alt",
  "uil-grin-tongue-wink",
  "uil-grin",
  "uil-hdd",
  "uil-headphones-alt",
  "uil-headphones",
  "uil-heart-alt",
  "uil-heart-medical",
  "uil-heart-rate",
  "uil-heart-sign",
  "uil-heart",
  "uil-heartbeat",
  "uil-history-alt",
  "uil-history",
  "uil-home-alt",
  "uil-home",
  "uil-horizontal-align-center",
  "uil-horizontal-align-left",
  "uil-horizontal-align-right",
  "uil-horizontal-distribution-center",
  "uil-horizontal-distribution-left",
  "uil-horizontal-distribution-right",
  "uil-hourglass",
  "uil-html3-alt",
  "u uil-html3",
  "uil-hunting",
  "uil-image-alt-slash",
  "uil-image-block",
  "uil-image-broken",
  "uil-image-check",
  "uil-image-download",
  "uil-image-edit",
  "uil-image-lock",
  "uil-image-minus",
  "uil-image-plus",
  "uil-image-question",
  "uil-image-redo",
  "uil-image-resize-landscape",
  "uil-image-resize-square",
  "uil-image-search",
  "uil-image-share",
  "uil-image-shield",
  "uil-image-slash",
  "uil-image-times",
  "uil-image-upload",
  "uil-image-v",
  "uil-image",
  "uil-images",
  "uil-import",
  "uil-incoming-call",
  "uil-info-circle",
  "uil-instagram-alt",
  "uil-instagram",
  "uil-intercom-alt",
  "uil-intercom",
  "uil-invoice",
  "uil-italic",
  "uil-jackhammer",
  "uil-java-script",
  "uil-kayak",
  "uil-key-skeleton-alt",
  "uil-key-skeleton",
  "uil-keyboard-alt",
  "uil-keyboard-hide",
  "uil-keyboard-show",
  "uil-keyboard",
  "uil-keyhole-circle",
  "uil-keyhole-square-full",
  "uil-keyhole-square",
  "uil-kid",
  "uil-label-alt",
  "uil-label",
  "uil-lamp",
  "uil-laptop-cloud",
  "uil-laptop",
  "uil-laughing",
  "uil-layer-group-slash",
  "uil-layer-group",
  "uil-layers-alt",
  "uil-layers-slash",
  "uil-layers",
  "uil-left-arrow-from-left",
  "uil-left-arrow-to-left",
  "uil-left-indent-alt",
  "uil-left-indent",
  "uil-left-to-right-text-direction",
  "uil-life-ring",
  "uil-lightbulb-alt",
  "uil-lightbulb",
  "uil-line-alt",
  "uil-line-spacing",
  "uil-line",
  "uil-link-alt",
  "uil-link-broken",
  "uil-link-h",
  "uil-link",
  "uil-linkedin-alt",
  "uil-linkedin",
  "uil-list-ui-alt",
  "uil-list-ul",
  "uil-location-arrow-alt",
  "uil-location-arrow",
  "uil-location-pin-alt",
  "uil-location-point",
  "uil-lock-access",
  "uil-lock-alt",
  "uil-lock-open-alt",
  "uil-lock-slash",
  "uil-lock",
  "uil-mailbox-alt",
  "uil-mailbox",
  "uil-map-marker-alt",
  "uil-map-marker-edit",
  "uil-map-marker-info",
  "uil-map-marker-minus",
  "uil-map-marker-plus",
  "uil-map-marker-question",
  "uil-map-marker-shield",
  "uil-map-marker-slash",
  "uil-map-marker",
  "uil-map-pin-alt",
  "uil-map-pin",
  "uil-map",
  "uil-mars",
  "uil-master-card",
  "uil-maximize-left",
  "uil-medal",
  "uil-medical-drip",
  "uil-medical-square-full",
  "uil-medical-square",
  "uil-medium-m",
  "uil-medkit",
  "uil-meeting-board",
  "uil-megaphone",
  "uil-meh-alt",
  "uil-meh-closed-eye",
  "uil-meh",
  "uil-message",
  "uil-metro",
  "uil-microphone-slash",
  "uil-microphone",
  "uil-minus-circle",
  "uil-minus-path",
  "uil-minus-square-full",
  "uil-minus-square",
  "uil-minus",
  "uil-java-script",
  "uil-missed-call",
  "uil-mobile-android-alt",
  "uil-mobile-android",
  "uil-mobile-vibrate",
  "uil-modem",
  "uil-money-bill-stack",
  "uil-money-bill",
  "uil-money-insert",
  "uil-money-stack",
  "uil-money-withdraw",
  "uil-money-withdrawal",
  "uil-moneybag-alt",
  "uil-moneybag",
  "uil-monitor-heart-rate",
  "uil-monitor",
  "uil-moon-eclipse",
  "uil-moon",
  "uil-moonset",
  "uil-mountains-sun",
  "uil-mountains",
  "uil-mouse-alt",
  "uil-mouse",
  "uil-music-note",
  "uil-music-tune-slash",
  "uil-music",
  "uil-n-a",
  "uil-navigator",
  "uil-nerd",
  "uil-newspaper",
  "uil-ninja",
  "uil-no-entry",
  "uil-notebooks",
  "uil-notes",
  "uil-object-group",
  "uil-object-ungroup",
  "uil-octagon",
  "uil-opera-alt",
  "uil-opera",
  "uil-outgoing-call",
  "uil-package",
  "uil-padlock",
  "uil-paint-tool",
  "uil-palette",
  "uil-panorama-h-alt",
  "uil-panorama-h",
  "uil-panorama-v",
  "uil-paperclip",
  "uil-paragraph",
  "uil-parcel",
  "uil-parking-square",
  "uil-pathfinder-unite",
  "uil-pathfinder",
  "uil-pause-circle",
  "uil-pause",
  "uil-paypal",
  "uil-pen",
  "uil-pentagon",
  "uil-percentage",
  "uil-phone-alt",
  "uil-phone-pause",
  "uil-phone-slash",
  "uil-phone-times",
  "uil-phone-volume",
  "uil-phone",
  "uil-picture",
  "uil-plane-arrival",
  "uil-plane-departure",
  "uil-plane-fly",
  "uil-plane",
  "uil-play-circle",
  "uil-play",
  "uil-plug",
  "uil-plus-circle",
  "uil-plus-square",
  "uil-plus",
  "uil-podium",
  "uil-polygon",
  "uil-post-stamp",
  "uil-postcard",
  "uil-pound-circle",
  "uil-pound",
  "uil-power",
  "uil-prescription-bottle",
  "uil-presentation-check",
  "uil-presentation-edit",
  "uil-presentation-line",
  "uil-presentation-lines-alt",
  "uil-presentation-minus",
  "uil-presentation-play",
  "uil-presentation-plus",
  "uil-presentation-times",
  "uil-presentation",
  "uil-previous",
  "uil-pricetag-alt",
  "uil-print-slash",
  "uil-print",
  "uil-process",
  "uil-processor",
  "uil-pump",
  "uil-puzzle-piece",
  "uil-question-circle",
  "uil-rainbow",
  "uil-raindrops-alt",
  "uil-raindrops",
  "uil-react",
  "uil-receipt-alt",
  "uil-receipt",
  "uil-record-audio",
  "uil-reddit-alien-alt",
  "uil-redo",
  "uil-refresh",
  "uil-registered",
  "uil-repeat",
  "uil-restaurant",
  "uil-right-indent-alt",
  "uil-right-to-left-text-direction",
  "uil-robot",
  "uil-rope-way",
  "uil-rotate-360",
  "uil-rss-alt",
  "uil-rss-interface",
  "uil-rss",
  "uil-ruler-combined",
  "uil-ruler",
  "uil-sad-cry",
  "uil-sad-crying",
  "uil-sad-dizzy",
  "uil-sad",
  "uil-scaling-left",
  "uil-scaling-right",
  "uil-scenery",
  "uil-schedule",
  "uil-scroll-h",
  "uil-scroll",
  "uil-search-alt",
  "uil-search-minus",
  "uil-search-plus",
  "uil-search",
  "uil-selfie",
  "uil-server-alt",
  "uil-server-connection",
  "uil-server-network-alt",
  "uil-server-network",
  "uil-server",
  "uil-servicemark",
  "uil-share-alt",
  "uil-shield-check",
  "uil-shield-exclamation",
  "uil-shield-question",
  "uil-shield-slash",
  "uil-shield",
  "uil-ship",
  "uil-shop",
  "uil-shopping-basket",
  "uil-shopping-cart-alt",
  "uil-shovel",
  "uil-shrink",
  "uil-shuffle",
  "uil-shutter-alt",
  "uil-shutter",
  "uil-sick",
  "uil-sigma",
  "uil-sign-alt",
  "uil-sign-in-alt",
  "uil-sign-left",
  "uil-sign-out-alt",
  "uil-sign-right",
  "uil-signal-alt-3",
  "uil-signal-alt",
  "uil-signal",
  "uil-silence",
  "uil-silent-squint",
  "uil-sim-card",
  "uil-sitemap",
  "uil-skip-forward-alt",
  "uil-skip-forward-circle",
  "uil-skip-forward",
  "uil-skype-alt",
  "uil-skype",
  "uil-slack-alt",
  "uil-slack",
  "uil-sliders-v-alt",
  "uil-sliders-v",
  "uil-smile-beam",
  "uil-smile-dizzy",
  "uil-smile-squint-wink-alt",
  "uil-smile-squint-wink",
  "uil-smile-wink-alt",
  "uil-smile-wink",
  "uil-smile",
  "uil-snapchat-alt",
  "uil-snapchat-ghost",
  "uil-snapchat-square",
  "uil-snow-flake",
  "uil-snowflake-alt",
  "uil-snowflake",
  "uil-sort-amount-down",
  "uil-sort-amount-up",
  "uil-sort",
  "uil-sorting",
  "uil-space-key",
  "uil-spade",
  "uil-sperms",
  "uil-spin",
  "uil-square-full",
  "uil-square-shape",
  "uil-squint",
  "uil-star-half-alt",
  "uil-star",
  "uil-step-backward-alt",
  "uil-step-backward-circle",
  "uil-step-backward",
  "uil-step-forward",
  "uil-stop-circle",
  "uil-stopwatch-slash",
  "uil-stopwatch",
  "uil-store-alt",
  "uil-store",
  "uil-streering",
  "uil-stretcher",
  "uil-subject",
  "uil-subway-alt",
  "uil-subway",
  "uil-suitcase-alt",
  "uil-suitcase",
  "uil-sun",
  "uil-sunset",
  "uil-surprise",
  "uil-swatchbook",
  "uil-swiggy",
  "uil-swimmer",
  "uil-sync-exclamation",
  "uil-sync-slash",
  "uil-sync",
  "uil-syringe",
  "uil-table",
  "uil-tablet",
  "uil-tablets",
  "uil-tachometer-fast",
  "uil-tag-alt",
  "uil-tag",
  "uil-tape",
  "uil-taxi",
  "uil-tear",
  "uil-telegram-alt",
  "uil-telegram",
  "uil-telescope",
  "uil-temperature-empty",
  "uil-temperature-half",
  "uil-temperature-minus",
  "uil-temperature-plus",
  "uil-temperature-quarter",
  "uil-temperature-three-quarter",
  "uil-temperature",
  "uil-text-fields",
  "uil-text-size",
  "uil-text-strike-through",
  "uil-text",
  "uil-th-large",
  "uil-th-slash",
  "uil-th",
  "uil-thermometer",
  "uil-thumbs-down",
  "uil-thumbs-up",
  "uil-thunderstorm-moon",
  "uil-thunderstorm-sun",
  "uil-thunderstorm",
  "uil-ticket",
  "uil-times-circle",
  "uil-times-square",
  "uil-times",
  "uil-toggle-off",
  "uil-toggle-on",
  "uil-top-arrow-from-top",
  "uil-top-arrow-to-top",
  "uil-tornado",
  "uil-trademark-circle",
  "uil-trademark",
  "uil-traffic-barrier",
  "uil-trash-alt",
  "uil-trash",
  "uil-trees",
  "uil-triangle",
  "uil-trophy",
  "uil-truck-loading",
  "uil-truck",
  "uil-tumblr-alt",
  "uil-tumblr-square",
  "uil-tumblr",
  "uil-tv-retro-slash",
  "uil-tv-retro",
  "uil-twitter-alt",
  "uil-twitter",
  "uil-umbrella",
  "uil-unamused",
  "uil-underline",
  "uil-university",
  "uil-unlock-alt",
  "uil-unlock",
  "uil-upload-alt",
  "uil-upload",
  "uil-usd-circle",
  "uil-usd-square",
  "uil-user-check",
  "uil-user-circle",
  "uil-user-exclamation",
  "uil-user-minus",
  "uil-user-plus",
  "uil-user-square",
  "uil-user-times",
  "uil-user",
  "uil-users-alt",
  "uil-utensils-alt",
  "uil-utensils",
  "uil-vector-square-alt",
  "uil-vector-square",
  "uil-vertical-align-bottom",
  "uil-vertical-align-center",
  "uil-vertical-align-top",
  "uil-vertical-distribute-bottom",
  "uil-vertical-distribution-center",
  "uil-vertical-distribution-top",
  "uil-video-slash",
  "uil-video",
  "uil-visual-studio",
  "uil-vk-alt",
  "uil-vk",
  "uil-voicemail-rectangle",
  "uil-voicemail",
  "uil-volleyball",
  "uil-volume-down",
  "uil-volume-mute",
  "uil-volume-off",
  "uil-volume-up",
  "uil-volume",
  "uil-vuejs-alt",
  "uil-vuejs",
  "uil-wall",
  "uil-wallet",
  "uil-watch-alt",
  "uil-square",
  "uil-watch",
  "uil-water-drop-slash",
  "uil-water-glass",
  "uil-water",
  "uil-web-section-alt",
  "uil-web-section",
  "uil-webcam",
  "uil-weight",
  "uil-whatsapp",
  "uil-wheel-barrow",
  "uil-wheelchair-alt",
  "uil-wheelchair",
  "uil-wifi-router",
  "uil-wifi-slash",
  "uil-wifi",
  "uil-wind-moon",
  "uil-wind-sun",
  "uil-wind",
  "uil-window-maximize",
  "uil-window-section",
  "uil-window",
  "uil-windsock",
  "uil-wrap-text",
  "uuil-wrench",
  "uil-square",
  "uil-yen-circle",
  "uil-yen",
  "uil-yin-yang",
  "uil-youtube",
  "uil-0-plus",
  "uil-10-plus",
  "uil-12-plus",
  "uil-13-plus",
  "uil-16-plus",
  "uil-17-plus",
  "uil-18-plus",
  "uil-21-plus",
  "uil-3-plus",
  "uil-500px",
  "uil-6-plus",
  "mdi mdi-book-account",
  "mdi mdi-book-account-outline",
  "mdi mdi-cable-data",
  "mdi mdi-car-arrow-left",
  "mdi mdi-car-arrow-right",
  "mdi mdi-cellphone-charging",
  "mdi mdi-circle-half",
  "mdi mdi-circle-half-full",
  "mdi mdi-close-thick",
  "mdi mdi-escalator-box",
  "mdi mdi-hand-water",
  "mdi mdi-home-search",
  "mdi mdi-home-search-outline",
  "mdi mdi-human-baby-changing-table",
  "mdi mdi-human-male-child",
  "mdi mdi-human-wheelchair",
  "mdi mdi-lipstick",
  "mdi mdi-lock-check",
  "mdi mdi-lock-open-alert",
  "mdi mdi-lock-open-check",
  "mdi mdi-microsoft-access",
  "mdi mdi-microsoft-excel",
  "mdi mdi-microsoft-powerpoint",
  "mdi mdi-microsoft-sharepoint",
  "mdi mdi-microsoft-word",
  "mdi mdi-monitor-eye",
  "mdi mdi-nintendo-game-boy",
  "mdi mdi-order-bool-descending",
  "mdi mdi-recycle-variant",
  "mdi mdi-rocket-outline",
  "mdi mdi-size-l",
  "mdi mdi-size-m",
  "mdi mdi-size-s",
  "mdi mdi-size-xl",
  "mdi mdi-size-xs",
  "mdi mdi-size-xxl",
  "mdi mdi-size-xxs",
  "mdi mdi-size-xxxl",
  "mdi mdi-sort-bool-ascending",
  "mdi mdi-sort-bool-ascending-variant",
  "mdi mdi-sort-bool-descending",
  "mdi mdi-sort-bool-descending-variant",
  "mdi mdi-sort-numeric-ascending",
  "mdi mdi-sort-numeric-descending",
  "mdi mdi-stairs-box",
  "mdi mdi-table-refresh",
  "mdi mdi-table-sync",
  "mdi mdi-ticket-confirmation-outline",
  "mdi mdi-timer",
  "mdi mdi-timer-off",
  "mdi mdi-book-account",
  "mdi mdi-book-account-outline",
  "mdi mdi-cable-data",
  "mdi mdi-car-arrow-left",
  "mdi mdi-car-arrow-right",
  "mdi mdi-cellphone-charging",
  "mdi mdi-circle-half",
  "mdi mdi-circle-half-full",
  "mdi mdi-close-thick",
  "mdi mdi-escalator-box",
  "mdi mdi-hand-water",
  "mdi mdi-home-search",
  "mdi mdi-home-search-outline",
  "mdi mdi-human-baby-changing-table",
  "mdi mdi-human-male-child",
  "mdi mdi-human-wheelchair",
  "mdi mdi-lipstick",
  "mdi mdi-lock-check",
  "mdi mdi-lock-open-alert",
  "mdi mdi-lock-open-check",
  "mdi mdi-microsoft-access",
  "mdi mdi-microsoft-excel",
  "mdi mdi-microsoft-powerpoint",
  "mdi mdi-microsoft-sharepoint",
  "mdi mdi-microsoft-word",
  "mdi mdi-monitor-eye",
  "mdi mdi-nintendo-game-boy",
  "mdi mdi-order-bool-descending",
  "mdi mdi-recycle-variant",
  "mdi mdi-rocket-outline",
  "mdi mdi-size-l",
  "mdi mdi-size-m",
  "mdi mdi-size-s",
  "mdi mdi-size-xl",
  "mdi mdi-size-xs",
  "mdi mdi-size-xxl",
  "mdi mdi-size-xxs",
  "mdi mdi-size-xxxl",
  "mdi mdi-sort-bool-ascending",
  "mdi mdi-sort-bool-ascending-variant",
  "mdi mdi-sort-bool-descending",
  "mdi mdi-sort-bool-descending-variant",
  "mdi mdi-sort-numeric-ascending",
  "mdi mdi-sort-numeric-descending",
  "mdi mdi-stairs-box",
  "mdi mdi-table-refresh",
  "mdi mdi-table-sync",
  "mdi mdi-ticket-confirmation-outline",
  "mdi mdi-timer",
  "mdi mdi-timer-off",
  "dripicons-alarm",
  "dripicons-align-center",
  "dripicons-align-justify",
  "dripicons-align-left",
  "dripicons-align-right",
  "dripicons-anchor",
  "dripicons-archive",
  "dripicons-arrow-down",
  "dripicons-arrow-left",
  "dripicons-arrow-right",
  "dripicons-arrow-thin-down",
  "dripicons-arrow-thin-left",
  "dripicons-arrow-thin-right",
  "dripicons-arrow-thin-up",
  "dripicons-arrow-up",
  "dripicons-backspace",
  "dripicons-basket",
  "dripicons-basketball",
  "dripicons-battery-empty",
  "dripicons-battery-full",
  "dripicons-battery-low",
  "dripicons-battery-medium",
  "dripicons-bell",
  "dripicons-blog",
  "dripicons-bluetooth",
  "dripicons-bold",
  "dripicons-bookmark",
  "dripicons-bookmarks",
  "dripicons-box",
  "dripicons-briefcase",
  "dripicons-brightness-low",
  "dripicons-brightness-max",
  "dripicons-brightness-medium",
  "dripicons-broadcast",
  "dripicons-browser",
  "dripicons-browser-upload",
  "dripicons-brush",
  "dripicons-calendar",
  "dripicons-camcorder",
  "dripicons-camera",
  "dripicons-card",
  "dripicons-cart",
  "dripicons-checklist",
  "dripicons-checkmark",
  "dripicons-chevron-down",
  "dripicons-chevron-left",
  "dripicons-chevron-right",
  "dripicons-chevron-up",
  "dripicons-clipboard",
  "dripicons-clock",
  "dripicons-clockwise",
  "dripicons-cloud",
  "dripicons-cloud-download",
  "dripicons-cloud-upload",
  "dripicons-code",
  "dripicons-contract",
  "dripicons-contract-2",
  "dripicons-conversation",
  "dripicons-copy",
  "dripicons-crop",
  "dripicons-cross",
  "dripicons-crosshair",
  "dripicons-cutlery",
  "dripicons-device-desktop",
  "dripicons-device-mobile",
  "dripicons-device-tablet",
  "dripicons-direction",
  "dripicons-disc",
  "dripicons-document",
  "dripicons-document-delete",
  "dripicons-document-edit",
  "dripicons-document-new",
  "dripicons-document-remove",
  "dripicons-dot",
  "dripicons-dots-2",
  "dripicons-dots-3",
  "dripicons-download",
  "dripicons-duplicate",
  "dripicons-enter",
  "dripicons-exit",
  "dripicons-expand",
  "dripicons-expand-2",
  "dripicons-experiment",
  "dripicons-export",
  "dripicons-feed",
  "dripicons-flag",
  "dripicons-flashlight",
  "dripicons-folder",
  "dripicons-folder-open",
  "dripicons-forward",
  "dripicons-gaming",
  "dripicons-gear",
  "dripicons-graduation",
  "dripicons-graph-bar",
  "dripicons-graph-line",
  "dripicons-graph-pie",
  "dripicons-headset",
  "dripicons-heart",
  "dripicons-help",
  "dripicons-home",
  "dripicons-hourglass",
  "dripicons-inbox",
  "dripicons-information",
  "dripicons-italic",
  "dripicons-jewel",
  "dripicons-lifting",
  "dripicons-lightbulb",
  "dripicons-link",
  "dripicons-link-broken",
  "dripicons-list",
  "dripicons-loading",
  "dripicons-location",
  "dripicons-lock",
  "dripicons-lock-open",
  "dripicons-mail",
  "dripicons-map",
  "dripicons-media-loop",
  "dripicons-media-next",
  "dripicons-media-pause",
  "dripicons-media-play",
  "dripicons-media-previous",
  "dripicons-media-record",
  "dripicons-media-shuffle",
  "dripicons-media-stop",
  "dripicons-medical",
  "dripicons-menu",
  "dripicons-message",
  "dripicons-meter",
  "dripicons-microphone",
  "dripicons-minus",
  "dripicons-monitor",
  "dripicons-move",
  "dripicons-music",
  "dripicons-network-1",
  "dripicons-network-2",
  "dripicons-network-3",
  "dripicons-network-4",
  "dripicons-network-5",
  "dripicons-pamphlet",
  "dripicons-paperclip",
  "dripicons-pencil",
  "dripicons-phone",
  "dripicons-photo",
  "dripicons-photo-group",
  "dripicons-pill",
  "dripicons-pin",
  "dripicons-plus",
  "dripicons-power",
  "dripicons-preview",
  "dripicons-print",
  "dripicons-pulse",
  "dripicons-question",
  "dripicons-reply",
  "dripicons-reply-all",
  "dripicons-return",
  "dripicons-retweet",
  "dripicons-rocket",
  "dripicons-scale",
  "dripicons-search",
  "dripicons-shopping-bag",
  "dripicons-skip",
  "dripicons-stack",
  "dripicons-star",
  "dripicons-stopwatch",
  "dripicons-store",
  "dripicons-suitcase",
  "dripicons-swap",
  "dripicons-tag",
  "dripicons-tag-delete",
  "dripicons-tags",
  "dripicons-thumbs-down",
  "dripicons-thumbs-up",
  "dripicons-ticket",
  "dripicons-time-reverse",
  "dripicons-to-do",
  "dripicons-toggles",
  "dripicons-trash",
  "dripicons-trophy",
  "dripicons-upload",
  "dripicons-user",
  "dripicons-user-group",
  "dripicons-user-id",
  "dripicons-vibrate",
  "dripicons-view-apps",
  "dripicons-view-list",
  "dripicons-view-list-large",
  "dripicons-view-thumb",
  "dripicons-volume-full",
  "dripicons-volume-low",
  "dripicons-volume-medium",
  "dripicons-volume-off",
  "dripicons-wallet",
  "dripicons-warning",
  "dripicons-web",
  "dripicons-weight",
  "dripicons-wifi",
  "dripicons-wrong",
  "dripicons-zoom-in",
  "dripicons-zoom-out",
  "fas fa-grin",
  "fab fa-accessible-icon",
  "fab fa-accusoft",
  "fab fa-acquisitions-incorporated",
  "far fa-address-book",
  "far fa-address-card",
  "fab fa-adn",
  "fab fa-adobe",
  "fab fa-adversal",
  "fab fa-affiliatetheme",
  "fab fa-airbnb",
  "fab fa-algolia",
  "fab fa-alipay",
  "fab fa-amazon",
  "fab fa-amazon-pay",
  "fab fa-amilia",
  "fab fa-android",
  "fab fa-angellist",
  "far fa-angry",
  "fab fa-angrycreative",
  "fab fa-angular",
  "fab fa-app-store",
  "fab fa-app-store-ios",
  "fab fa-apper",
  "fab fa-apple",
  "fab fa-apple-pay",
  "far fa-arrow-alt-circle-down",
  "far fa-arrow-alt-circle-left",
  "far fa-arrow-alt-circle-right",
  "far fa-arrow-alt-circle-up",
  "fab fa-artstation",
  "fab fa-asymmetrik",
  "fab fa-atlassian",
  "fab fa-audible",
  "fab fa-autoprefixer",
  "fab fa-avianex",
  "fab fa-aviato",
  "fab fa-aws",
  "fab fa-bandcamp",
  "fab fa-battle-net",
  "fab fa-behance",
  "fab fa-behance-square",
  "far fa-bell",
  "far fa-bell-slash",
  "fab fa-bimobject",
  "fab fa-bitbucket",
  "fab fa-bitcoin",
  "fab fa-bity",
  "fab fa-black-tie",
  "fab fa-blackberry",
  "fab fa-blogger",
  "fab fa-blogger-b",
  "fab fa-bluetooth",
  "fab fa-bluetooth-b",
  "far fa-bookmark",
  "fab fa-bootstrap",
  "fab fa-btc",
  "fab fa-buffer",
  "far fa-building",
  "fab fa-buromobelexperte",
  "fab fa-buy-n-large",
  "fab fa-buysellads",
  "far fa-calendar",
  "far fa-calendar-alt",
  "far fa-calendar-check",
  "far fa-calendar-minus",
  "far fa-calendar-plus",
  "far fa-calendar-times",
  "fab fa-canadian-maple-leaf",
  "far fa-caret-square-down",
  "far fa-caret-square-left",
  "far fa-caret-square-right",
  "far fa-caret-square-up",
  "fab fa-cc-amazon-pay",
  "fab fa-cc-amex",
  "fab fa-cc-apple-pay",
  "fab fa-cc-diners-club",
  "fab fa-cc-discover",
  "fab fa-cc-jcb",
  "fab fa-cc-mastercard",
  "fab fa-cc-paypal",
  "fab fa-cc-stripe",
  "fab fa-cc-visa",
  "fab fa-centercode",
  "fab fa-centos",
  "far fa-chart-bar",
  "far fa-check-circle",
  "far fa-check-square",
  "fab fa-chrome",
  "fab fa-chromecast",
  "far fa-circle",
  "far fa-clipboard",
  "far fa-clock",
  "far fa-clone",
  "far fa-closed-captioning",
  "fab fa-cloudscale",
  "fab fa-cloudsmith",
  "fab fa-cloudversify",
  "fab fa-codepen",
  "fab fa-codiepie",
  "far fa-comment",
  "far fa-comment-alt",
  "far fa-comment-dots",
  "far fa-comments",
  "far fa-compass",
  "fab fa-confluence",
  "fab fa-connectdevelop",
  "fab fa-contao",
  "far fa-copy",
  "far fa-copyright",
  "fab fa-cotton-bureau",
  "fab fa-cpanel",
  "fab fa-creative-commons",
  "fab fa-creative-commons-by",
  "fab fa-creative-commons-nc",
  "fab fa-creative-commons-nc-eu",
  "fab fa-creative-commons-nc-jp",
  "fab fa-creative-commons-nd",
  "fab fa-creative-commons-pd",
  "fab fa-creative-commons-pd-alt",
  "fab fa-creative-commons-remix",
  "fab fa-creative-commons-sa",
  "fab fa-creative-commons-sampling",
  "fab fa-creative-commons-sampling-plus",
  "fab fa-creative-commons-share",
  "fab fa-creative-commons-zero",
  "far fa-credit-card",
  "fab fa-critical-role",
  "fab fa-css3",
  "fab fa-css3-alt",
  "fab fa-cuttlefish",
  "fab fa-d-and-d",
  "fab fa-d-and-d-beyond",
  "fab fa-dailymotion",
  "fab fa-dashcube",
  "fab fa-delicious",
  "fab fa-deploydog",
  "fab fa-deskpro",
  "fab fa-dev",
  "fab fa-deviantart",
  "fab fa-dhl",
  "fab fa-diaspora",
  "fab fa-digg",
  "fab fa-digital-ocean",
  "fab fa-discord",
  "fab fa-discourse",
  "far fa-dizzy",
  "fab fa-dochub",
  "fab fa-docker",
  "far fa-dot-circle",
  "fab fa-draft2digital",
  "fab fa-dribbble",
  "fab fa-dribbble-square",
  "fab fa-dropbox",
  "fab fa-drupal",
  "fab fa-dyalog",
  "fab fa-earlybirds",
  "fab fa-ebay",
  "fab fa-edge",
  "far fa-edit",
  "fab fa-elementor",
  "fab fa-ello",
  "fab fa-ember",
  "fab fa-empire",
  "far fa-envelope",
  "far fa-envelope-open",
  "fab fa-envira",
  "fab fa-erlang",
  "fab fa-ethereum",
  "fab fa-etsy",
  "fab fa-evernote",
  "fab fa-expeditedssl",
  "far fa-eye",
  "far fa-eye-slash",
  "fab fa-facebook",
  "fab fa-facebook-f",
  "fab fa-facebook-messenger",
  "fab fa-facebook-square",
  "fab fa-fantasy-flight-games",
  "fab fa-fedex",
  "fab fa-fedora",
  "fab fa-figma",
  "far fa-file",
  "far fa-file-alt",
  "far fa-file-archive",
  "far fa-file-audio",
  "far fa-file-code",
  "far fa-file-excel",
  "far fa-file-image",
  "far fa-file-pdf",
  "far fa-file-powerpoint",
  "far fa-file-video",
  "far fa-file-word",
  "fab fa-firefox",
  "fab fa-firefox-browser",
  "fab fa-first-order",
  "fab fa-first-order-alt",
  "fab fa-firstdraft",
  "far fa-flag",
  "fab fa-flickr",
  "fab fa-flipboard",
  "far fa-flushed",
  "fab fa-fly",
  "far fa-folder",
  "far fa-folder-open",
  "fab fa-font-awesome",
  "fab fa-font-awesome-alt",
  "fab fa-font-awesome-flag",
  "fab fa-fonticons",
  "fab fa-fonticons-fi",
  "fab fa-fort-awesome",
  "fab fa-fort-awesome-alt",
  "fab fa-forumbee",
  "fab fa-foursquare",
  "fab fa-free-code-camp",
  "fab fa-freebsd",
  "far fa-frown",
  "far fa-frown-open",
  "fab fa-fulcrum",
  "far fa-futbol",
  "fab fa-galactic-republic",
  "fab fa-galactic-senate",
  "far fa-gem",
  "fab fa-get-pocket",
  "fab fa-gg",
  "fab fa-gg-circle",
  "fab fa-git",
  "fab fa-git-alt",
  "fab fa-git-square",
  "fab fa-github",
  "fab fa-github-alt",
  "fab fa-github-square",
  "fab fa-gitkraken",
  "fab fa-gitlab",
  "fab fa-gitter",
  "fab fa-glide",
  "fab fa-glide-g",
  "fab fa-gofore",
  "fab fa-goodreads",
  "fab fa-goodreads-g",
  "fab fa-google",
  "fab fa-google-drive",
  "fab fa-google-play",
  "fab fa-google-plus",
  "fab fa-google-plus-g",
  "fab fa-google-plus-square",
  "fab fa-google-wallet",
  "fab fa-gratipay",
  "fab fa-grav",
  "far fa-grimace",
  "far fa-grin",
  "far fa-grin-alt",
  "far fa-grin-beam",
  "far fa-grin-beam-sweat",
  "far fa-grin-hearts",
  "far fa-grin-squint",
  "far fa-grin-squint-tears",
  "far fa-grin-stars",
  "far fa-grin-tears",
  "far fa-grin-tongue",
  "far fa-grin-tongue-squint",
  "far fa-grin-tongue-wink",
  "far fa-grin-wink",
  "fab fa-gripfire",
  "fab fa-grunt",
  "fab fa-gulp",
  "fab fa-hacker-news",
  "fab fa-hacker-news-square",
  "fab fa-hackerrank",
  "far fa-hand-lizard",
  "far fa-hand-paper",
  "far fa-hand-peace",
  "far fa-hand-point-down",
  "far fa-hand-point-left",
  "far fa-hand-point-right",
  "far fa-hand-point-up",
  "far fa-hand-pointer",
  "far fa-hand-rock",
  "far fa-hand-scissors",
  "far fa-hand-spock",
  "far fa-handshake",
  "far fa-hdd",
  "far fa-heart",
  "fab fa-hips",
  "fab fa-hire-a-helper",
  "fab fa-hooli",
  "fab fa-hornbill",
  "far fa-hospital",
  "fab fa-hotjar",
  "far fa-hourglass",
  "fab fa-houzz",
  "fab fa-html5",
  "fab fa-hubspot",
  "far fa-id-badge",
  "far fa-id-card",
  "fab fa-ideal",
  "far fa-image",
  "far fa-images",
  "fab fa-imdb",
  "fab fa-instagram",
  "fab fa-instagram-square",
  "fab fa-intercom",
  "fab fa-internet-explorer",
  "fab fa-invision",
  "fab fa-ioxhost",
  "fab fa-itch-io",
  "fab fa-itunes",
  "fab fa-itunes-note",
  "fab fa-java",
  "fab fa-jedi-order",
  "fab fa-jenkins",
  "fab fa-jira",
  "fab fa-joget",
  "fab fa-joomla",
  "fab fa-js",
  "fab fa-js-square",
  "fab fa-jsfiddle",
  "fab fa-kaggle",
  "fab fa-keybase",
  "far fa-keyboard",
  "fab fa-keycdn",
  "fab fa-kickstarter",
  "fab fa-kickstarter-k",
  "far fa-kiss",
  "far fa-kiss-beam",
  "far fa-kiss-wink-heart",
  "fab fa-korvue",
  "fab fa-laravel",
  "fab fa-lastfm",
  "fab fa-lastfm-square",
  "far fa-laugh",
  "far fa-laugh-beam",
  "far fa-laugh-squint",
  "far fa-laugh-wink",
  "fab fa-leanpub",
  "far fa-lemon",
  "fab fa-less",
  "far fa-life-ring",
  "far fa-lightbulb",
  "fab fa-line",
  "fab fa-linkedin",
  "fab fa-linkedin-in",
  "fab fa-linode",
  "fab fa-linux",
  "far fa-list-alt",
  "fab fa-lyft",
  "fab fa-magento",
  "fab fa-mailchimp",
  "fab fa-mandalorian",
  "far fa-map",
  "fab fa-markdown",
  "fab fa-mastodon",
  "fab fa-maxcdn",
  "fab fa-mdb",
  "fab fa-medapps",
  "fab fa-medium",
  "fab fa-medium-m",
  "fab fa-medrt",
  "fab fa-meetup",
  "fab fa-megaport",
  "far fa-meh",
  "far fa-meh-blank",
  "far fa-meh-rolling-eyes",
  "fab fa-mendeley",
  "fab fa-microblog",
  "fab fa-microsoft",
  "far fa-minus-square",
  "fab fa-mix",
  "fab fa-mixcloud",
  "fab fa-mixer",
  "fab fa-mizuni",
  "fab fa-modx",
  "fab fa-monero",
  "far fa-money-bill-alt",
  "far fa-moon",
  "fab fa-napster",
  "fab fa-neos",
  "far fa-newspaper",
  "fab fa-nimblr",
  "fab fa-node",
  "fab fa-node-js",
  "fab fa-npm",
  "fab fa-ns8",
  "fab fa-nutritionix",
  "far fa-object-group",
  "far fa-object-ungroup",
  "fab fa-odnoklassniki",
  "fab fa-odnoklassniki-square",
  "fab fa-old-republic",
  "fab fa-opencart",
  "fab fa-openid",
  "fab fa-opera",
  "fab fa-optin-monster",
  "fab fa-orcid",
  "fab fa-osi",
  "fab fa-page4",
  "fab fa-pagelines",
  "fab fa-palfed",
  "far fa-paper-plane",
  "fab fa-patreon",
  "far fa-pause-circle",
  "fab fa-paypal",
  "fab fa-penny-arcade",
  "fab fa-periscope",
  "fab fa-phabricator",
  "fab fa-phoenix-framework",
  "fab fa-phoenix-squadron",
  "fab fa-php",
  "fab fa-pied-piper",
  "fab fa-pied-piper-alt",
  "fab fa-pied-piper-hat",
  "fab fa-pied-piper-pp",
  "fab fa-pied-piper-square",
  "fab fa-pinterest",
  "fab fa-pinterest-p",
  "fab fa-pinterest-square",
  "far fa-play-circle",
  "fab fa-playstation",
  "far fa-plus-square",
  "fab fa-product-hunt",
  "fab fa-pushed",
  "fab fa-python",
  "fab fa-qq",
  "far fa-question-circle",
  "fab fa-quinscape",
  "fab fa-quora",
  "fab fa-r-project",
  "fab fa-raspberry-pi",
  "fab fa-ravelry",
  "fab fa-react",
  "fab fa-reacteurope",
  "fab fa-readme",
  "fab fa-rebel",
  "fab fa-red-river",
  "fab fa-reddit",
  "fab fa-reddit-alien",
  "fab fa-reddit-square",
  "fab fa-redhat",
  "far fa-registered",
  "fab fa-renren",
  "fab fa-replyd",
  "fab fa-researchgate",
  "fab fa-resolving",
  "fab fa-rev",
  "fab fa-rocketchat",
  "fab fa-rockrms",
  "far fa-sad-cry",
  "far fa-sad-tear",
  "fab fa-safari",
  "fab fa-salesforce",
  "fab fa-sass",
  "far fa-save",
  "fab fa-schlix",
  "fab fa-scribd",
  "fab fa-searchengin",
  "fab fa-sellcast",
  "fab fa-sellsy",
  "fab fa-servicestack",
  "far fa-share-square",
  "fab fa-shirtsinbulk",
  "fab fa-shopify",
  "fab fa-shopware",
  "fab fa-simplybuilt",
  "fab fa-sistrix",
  "fab fa-sith",
  "fab fa-sketch",
  "fab fa-skyatlas",
  "fab fa-skype",
  "fab fa-slack",
  "fab fa-slack-hash",
  "fab fa-slideshare",
  "far fa-smile",
  "far fa-smile-beam",
  "far fa-smile-wink",
  "fab fa-snapchat",
  "fab fa-snapchat-ghost",
  "fab fa-snapchat-square",
  "far fa-snowflake",
  "fab fa-soundcloud",
  "fab fa-sourcetree",
  "fab fa-speakap",
  "fab fa-speaker-deck",
  "fab fa-spotify",
  "far fa-square",
  "fab fa-squarespace",
  "fab fa-stack-exchange",
  "fab fa-stack-overflow",
  "fab fa-stackpath",
  "far fa-star",
  "far fa-star-half",
  "fab fa-staylinked",
  "fab fa-steam",
  "fab fa-steam-square",
  "fab fa-steam-symbol",
  "fab fa-sticker-mule",
  "far fa-sticky-note",
  "far fa-stop-circle",
  "fab fa-strava",
  "fab fa-stripe",
  "fab fa-stripe-s",
  "fab fa-studiovinari",
  "fab fa-stumbleupon",
  "fab fa-stumbleupon-circle",
  "far fa-sun",
  "fab fa-superpowers",
  "fab fa-supple",
  "far fa-surprise",
  "fab fa-suse",
  "fab fa-swift",
  "fab fa-symfony",
  "fab fa-teamspeak",
  "fab fa-telegram",
  "fab fa-telegram-plane",
  "fab fa-tencent-weibo",
  "fab fa-the-red-yeti",
  "fab fa-themeco",
  "fab fa-themeisle",
  "fab fa-think-peaks",
  "far fa-thumbs-down",
  "far fa-thumbs-up",
  "far fa-times-circle",
  "far fa-tired",
  "fab fa-trade-federation",
  "far fa-trash-alt",
  "fab fa-trello",
  "fab fa-tripadvisor",
  "fab fa-tumblr",
  "fab fa-tumblr-square",
  "fab fa-twitch",
  "fab fa-twitter",
  "fab fa-twitter-square",
  "fab fa-typo3",
  "fab fa-uber",
  "fab fa-ubuntu",
  "fab fa-uikit",
  "fab fa-umbraco",
  "fab fa-uniregistry",
  "fab fa-unity",
  "fab fa-untappd",
  "fab fa-ups",
  "fab fa-usb",
  "far fa-user",
  "far fa-user-circle",
  "fab fa-usps",
  "fab fa-ussunnah",
  "fab fa-vaadin",
  "fab fa-viacoin",
  "fab fa-viadeo",
  "fab fa-viadeo-square",
  "fab fa-viber",
  "fab fa-vimeo",
  "fab fa-vimeo-square",
  "fab fa-vimeo-v",
  "fab fa-vine",
  "fab fa-vk",
  "fab fa-vnv",
  "fab fa-vuejs",
  "fab fa-waze",
  "fab fa-weebly",
  "fab fa-weibo",
  "fab fa-weixin",
  "fab fa-whatsapp",
  "fab fa-whatsapp-square",
  "fab fa-whmcs",
  "fab fa-wikipedia-w",
  "far fa-window-close",
  "far fa-window-maximize",
  "far fa-window-minimize",
  "far fa-window-restore",
  "fab fa-windows",
  "fab fa-wix",
  "fab fa-wizards-of-the-coast",
  "fab fa-wolf-pack-battalion",
  "fab fa-wordpress",
  "fab fa-wordpress-simple",
  "fab fa-wpbeginner",
  "fab fa-wpexplorer",
  "fab fa-wpforms",
  "fab fa-wpressr",
  "fab fa-xbox",
  "fab fa-xing",
  "fab fa-xing-square",
  "fab fa-y-combinator",
  "fab fa-yahoo",
  "fab fa-yammer",
  "fab fa-yandex",
  "fab fa-yandex-international",
  "fab fa-yarn",
  "fab fa-yelp",
  "fab fa-yoast",
  "fab fa-youtube",
  "fab fa-youtube-square",
  "fab fa-zhihu"
]