export const SET_IFRAME_WIDGET_VALUES = 'SET_IFRAME_WIDGET_VALUES';
export const FILTER_IFRAME_WIDGET_DEVICES = 'FILTER_IFRAME_WIDGET_DEVICES';
export const SET_IFRAME_WIDGET_EDIT_MODE = 'SET_IFRAME_WIDGET_EDIT_MODE';
export const SET_IFRAME_WIDGET_DATA = 'SET_IFRAME_WIDGET_DATA';